### ISSUE TITLE
프로젝트 리스트 쿼리 스트링 특수 문자 처리.

### ISSUE THREAD

**Issue by donghL-dev** [perfect-matching/perfectmatching-frontend#122]
* `/api/projects?tag=C#` 으로 보낼 경우, 특수문자를 인식하지 못해서 `C#`을 `C`로 처리하는 경우가 발생.

* 이 부분을 해결하기 위해 `C#` 태그를 보낼 때 #을 %23으로 문자 치환으로 보낼것을 권고함.

   * `/api/projects?tag=C%23`

**Comment by kwonyg** [comment]
Fixed
