### ISSUE TITLE
유저 프로필 페이지 데이터 폼 제안

### ISSUE THREAD

**Issue by donghL-dev** [perfect-matching/perfectmatching-frontend#44]
* 현재 테스트중인 [프론트 서버](https://perfectmatching.netlify.com/users/1)에서 데이터를 확인한 결과, 유저 프로필 페이지의 진행했던 프로젝트가 다음과 같이 나타납니다.
 
   ![image](https://user-images.githubusercontent.com/33312179/63519873-a8a40600-c52e-11e9-894e-908552b7c5f4.png)

* 진행중, 완료된 프로젝트 데이터에 대해서 현재 상세 설명 필드가 같이 페이지에 노출되는데, 상세 설명 필드는 프로젝트 상세 페이지에서만 확인 가능하도록 하는것이 어떨까 제안드립니다.

* 추가적인 질문 사항은, 현재 상단 사진에 리더의 정보가 표시되지 않는데, 추가 예정인지 질문드립니다.

**Comment by kwonyg** [comment]
- 완료된 프로젝트에는 상세설명이 있어야 할거 같은데..  성과나 업무같은걸 적는 컬럼으로 넣어놓은거라, 근데 상세페이지에서만 하려는 이유가 있나??

- 완료된 프로젝트는 리더정보 없는게 맞는거 같다. 우리플랫폼에서 진행했던 프로젝트가 아닐 수 있으니까 ㅎㅎ

**Comment by kwonyg** [comment]
![screencapture-localhost-8080-users-1-2019-08-22-23_37_46](https://user-images.githubusercontent.com/32382352/63523889-ebb5a780-c535-11e9-9bfb-5f6431bb45f2.png)

- 생각했던 유저 상세페이지는 위 사진같은 모습
- 프로젝트 관리 리스트 페이지에 있는 내용이 유저 상세페이지 아래에 똑같이 나오는 구조

**Comment by ssayebee** [comment]
자꾸 혼란이 있어서 그런데, 외부 프로젝트 도메인을 추가하는 것이 아니라 완료된 프로젝트라는 도메인을 추가하자는 말씀이신 가요?? 

현재 생각하고 있는 [ERD](https://drive.google.com/file/d/1tmBT3GAL3OIpRocH-hIGdo70-vzptTSo/view?usp=sharing)는 이런 형태인데, 제가 재대로 이해하고 있는게 맞는지 궁금합니다.!

**Comment by kwonyg** [comment]
외부 프로젝트랑 완료된 프로젝트를 둘 다 의미하는 도메인 하나를 만드는걸로 알고있었는데..? 

진행중이었던 프로젝트에서 '프로젝트 완료'버튼을 눌려 나오는 form 페이지랑 '프로젝트 추가하기' 버튼을 누르면 나오는 form 페이지가 같고. 이 form 페이지에서 post하는 데이터들은 우리가 새로 추가하기로한 도메인(외부, 완료된)으로 저장되는거로..! 그리고 이렇게 추가된 데이터는 저기 '진행했던 프로젝트' 섹션에 진열이 됨. 

아 그리고 학교에서 개발하는거면 언제언제 오는데? 그럼 나도 학교에서 개발을 진행할게

**Comment by kwonyg** [comment]
그럼 기존의 프로젝트 게시물은 어떻게 되는지 의문이 드는거라면, 이건 삭제하던지 아니면 status만 완료 라고 해서 그대로 둬도 될거 같다!

**Comment by ssayebee** [comment]
아 뭔가 이해된 부분이 달랐던것 같습니다. 전 따로 외부 프로젝트 도메인만 생성 하면 되고, 해당 부분은 DTO를 이용해서 처리한다고 이해했었는데,  좀 더 고민 해보겠습니다. 저희는 일단 내일 2시 이후에 학교에서 진행할 것 같아요 !

**Comment by kwonyg** [comment]
Good Good

**Comment by ssayebee** [comment]
[ERD](https://drive.google.com/file/d/1tmBT3GAL3OIpRocH-hIGdo70-vzptTSo/view?usp=sharing)에 해당 내용이 반영이 안되있었네요. 방금 추가했습니다.!
