### ISSUE TITLE
프로젝트 리스트 페이지에 대한 질문있습니다.

### ISSUE THREAD

**Issue by ssayebee** [perfect-matching/perfectmatching-frontend#51]
프론트 테스트 서버의 프로젝트 리스트 페이지를 확인하였는데, 6개 프로젝트가 카드형식 화면으로 채워지게 레이아웃이 잡혀있는 것을 확인하였습니다. 현재 offset별 응답 프로젝트 갯수가 4개인데 6개로 수정하는 것이 맞을까 질문드립니다.

**Comment by kwonyg** [comment]
어어 ㅎㅎ나도 불러오는 갯수 더 늘려야겠다는 생각 했었다 ㅎㅎ 6개보다는 더 많이 불러올려고 생각중

**Comment by ssayebee** [comment]
네 생각해보시고 알려주세요~!!
