### ISSUE TITLE
 일부 페이지를 제외하고 전부 메인페이지로 이동.

### ISSUE THREAD

**Issue by donghL-dev** [perfect-matching/perfectmatching-frontend#82]
* 명세에 나타나 있는 페이지 일부를 제외하고 전부 메인 페이지로 이동합니다.

* 이 부분은 현재 개선중인 상태인가요?

* 확인한 페이지는 마이페이지, 프로젝트 개설, 수정, 상세 페이지 입니다.

**Comment by kwonyg** [comment]
현재 임시로 로그인이 된 상태에서만 페이지 이동이 가능한 페이지는 로그인이 안되어있으면 홈화면으로 이동하게 되어있음.
차후 로그인 모달창을 띄울 예정

**Comment by kwonyg** [comment]
비로그인 상태에서 진입시 로그인 모달창이 뜨도록 변경
